name: PR Auto Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
